### ISSUE TITLE
Hope update to .Net Core support

### ISSUE THREAD

**Issue by hupo376787** [JsonCSharpClassGenerator/JsonCSharpClassGenerator#18] opened 2018-08-07 14:12 UTC
Hope update to .Net Core support, so this powerful tool can be used in uwp.

**Comment by suntong** [comment] 2018-08-07 14:18
Hm? .Net Core has been updated to the latest. 
Please elaborate.

**Comment by hupo376787** [comment] 2018-08-07 14:59
I tried to refer the project "JsonCSharpClassGeneratorLib" in my uwp solution, the vs report error.

![image](https://user-images.githubusercontent.com/14960168/43783956-8f2a1cec-9a95-11e8-9472-b34cd12391be.png)

**Comment by suntong** [comment] 2018-08-07 16:24
Sorry, I'm not an C#/VS expert. 

My basic understanding is that you get the JsonCSharpClassGenerator working by itself, but not with your own uwp solution. So this issue is beyond the scope of JsonCSharpClassGenerator. 

I'd say the problem is at your uwp solution.

**Comment by hupo376787** [comment] 2018-08-08 02:29
Sorry, I mean .net standard 2.0 support, not .net core.

**Comment by suntong** [comment] 2018-08-08 23:10
The .net 2.0 is quite a different beast than modern .net, and will not be supported by this project. 

Closing it now. The original JsonCSharpClassGenerator supports .net 2.0. You may tempt your luck with it. Mind you, I was not able to make .net 2.0 of the original JsonCSharpClassGenerator work myself.

**Closed as completed by suntong** 2018-08-08 23:10 UTC
