### ISSUE TITLE
Merge duplicated classes

### ISSUE THREAD

**Issue by UlyssesWu** [JsonCSharpClassGenerator/JsonCSharpClassGenerator#12] opened 2017-11-15 05:00 UTC
I noticed sometimes there are a lot of duplicated classes in generated files. Some are caused by slightly different definitions (since some fields may actually have default values so they are not recorded in json), but others are actually the same thing. Maybe a option to allow duplicated classes merging is useful in some cases.

![duplicated-json-class](https://user-images.githubusercontent.com/4312781/32819478-78ed60d6-ca04-11e7-82c5-c87dd37b4c37.png)

**Comment by sabarnett** [comment] 2017-11-17 10:46
Any chance you can post a sample file? It would make fixing this a lot easier.

**Comment by UlyssesWu** [comment] 2017-11-17 13:49
Here is an example json... I'm not sure whether those classes with numbers are actually essential or not.

[ShortExample.txt](https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/files/1482458/ShortExample.txt)

**Comment by sabarnett** [comment] 2017-11-17 16:13
Excellent, thank you. I’ll run this through and see what’s happening. The tool works on the premise that there will only be one example of any given class in the Json.

**Comment by suntong** [comment] 2017-11-18 04:37
Thank you @sabarnett for looking into this. I'm out of town and won't be back till the end of the month.

**Comment by sabarnett** [comment] 2017-11-19 12:38
I've raised a pull request for s change to support this:

https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/pull/13

Please note, the JSON file that @UlyssesWu attached was not syntactically correct JSON, so the parser rejected it. I cobbled together a replacement test file that, I believe, reproduced the problem. It generated multiple classes in the way described, and it doesn't any more. 

[ShortExample_sab.zip](https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/files/1485529/ShortExample_sab.zip)

I've attached the test file I have been using.

**Comment by UlyssesWu** [comment] 2017-11-20 02:45
Thank you @sabarnett !
I have tried it and it actually reduced the class file count from 1965 to 1123 for one of my test jsons.

But I noticed some issues: (I feel sorry about this because my last example wasn't showing these issues.)
- Sometimes a json object should be converted to a Dictionary (Key-Value pairs) but our tool generated many classes based on key. (using the new example below, `0000.cs` - `0109.cs`) Maybe it's too hard to distinguish this situation?
- Sometimes some classes which have been merged are still referenced in other classes. (`Content30.cs` : `Mesh16 `, `Content40.cs` : `Mesh24`, but there is only `Mesh.cs`)

Sorry again for my last example, I just wanted to cut it since it's too large, and actually it can be used in the [release build](https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/releases) here without error. Now I attached the full example here:

[pure.zip](https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/files/1486306/pure.zip)

**Comment by sabarnett** [comment] 2017-11-20 20:11
Ok, so I see the problem. It's generating a different class where the field names list is different and you have structures in the Json with the same name but differing property names, so it thinks they're different classes (it is a very simplistic system that assumes you always generate the same field list). 

I can deal with that by merging classes of the same name together, so "Content" for example, will contain all of the fields that all of the variations of "Content" have. I'm pretty sure that's what you are aiming at. That reduces the list to 178 distinct classes, most of which are the "0000", "0001" types. 

These are named fields in the Json, so I'm not sure what to do about them. They are legitimately classes in their own right because that's how the Json treats them. Going to need to think about that one a little, as the content of the class is the same, but the name needs to match the Json.

The merged class names was entirely my fault and will be fixed when I upload the code. The class generation code can put the class type in one of two places and I only updated one of them.

Many thanks for the file. It's been brilliant for sorting this out. I've also added a feedback message so you'll get some feedback when it's generating classes from such a large file. 

I'll get back to you when I have dealt with some of the other issues.

**Comment by sabarnett** [comment] 2017-11-23 18:46
I've updated my pull request with the latest code (hopefully - I'm no GitHub expert). 

This variant will merge classes. So, if I find a class called "Wombat" and a "Wombat2", I'll ensure that all the fields of "Wombat2" exist in "Wombat". That way, you end up with one class. The previous code only considered classes the same if the fields matched too.

This has vastly reduced the number of classes. However, there are still some "sort of" duplicates. An example is "Pv" and "Pv2". The name of the class is based off the property name in the Json so, while the properties of these two classes are the same, we cannot legitimately call them the same thing.

This is also why there are classes for "0000", "0001" and "0002" etc. The property name makes them different classes.

This can be dealt with, I believe. However, this isn't my project and it is a significant new feature, so @suntong needs to have input. 

That thing with the classes not being replaced properly has also been dealt with.

Sorry for the delay, the "day job" is somewhat hectic at the moment.

**Comment by UlyssesWu** [comment] 2017-11-24 01:36
Thanks @sabarnett , you have made it a better tool than Visual Studio's `Paste as Json classes`!
And I totally understand the pain of trapped in "day job".

I think it's almost enough for me (I can merge other classes manually), so if @suntong thinks so, I will close this issue after he comments here, and maybe I will try to make a pull request someday.

**Comment by suntong** [comment] 2017-11-28 19:19
Thanks A LOT @sabarnett. I concur with every decision you made, and totally agree with your judgement of leaving the significant new feature out from this issue to future enhancements. 

I updated the [Major enhancements since the fork](https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/wiki/Major-enhancements-since-the-fork#november-2017) to the best of my understanding. Please review it and see if it precisely summarizes the feature, and correct it if otherwise. 

@UlyssesWu, I'll leave you to close this issue if you are satisfied with the enhancements so far, and we are looking forward to your pull request in the future, as this GitHub fork is "[_a contribution based project_](https://github.com/JsonCSharpClassGenerator/JsonCSharpClassGenerator/wiki/About-the-JsonCSharpClassGenerator-GitHub-Fork-Project)" so that everyone can benefit from everyone else's improvements through our collaboration.

**Comment by sabarnett** [comment] 2017-11-28 20:27
Thanks @suntong. I was going to get to the documentation, honest!

There are still things we can do. In the example given, there are several classes generated with different names but the same fields. However, this is probably an enhancement too far at this stage, as we get in to issues like what the class should be called and whether we try to create dictionaries.

One for another day, I think.

Steve Barnett

**Closed as completed** 2017-11-29 01:56 UTC

**Comment by suntong** [comment] 2017-11-29 03:25
I know @sabarnett. I just want to show that I'm not entirely useless, ;-)
